#include "game.h"

#define PLAYER_LIVES_MAX 5

#define PLAYER_SPECIAL_MAX 4
#define PLAYER_FIRE_DELAY 8
#define PLAYER_FIRE_AUDIO_DELAY 10
#define PLAYER_SHIP_HEIGHT 16
#define PLAYER_SHIP_WIDTH 16
#define PLAYER_SHIP_ANIM_FRAMES 8
#define PLAYER_MOVE_SPEED 2
#define PLAYER_CENTER_OFFSET_X 8
#define PLAYER_CENTER_OFFSET_Y 8
#define PLAYER_HITBOX_OFFSET_X 5
#define PLAYER_HITBOX_OFFSET_Y 5
#define PLAYER_HITBOX_WIDTH 5
#define PLAYER_HITBOX_HEIGHT 5