#include "game.h"

#define PLAYER_LIVES_MAX 5
#define PLAYER_SPECIAL_MAX 4
#define PLAYER_SPECIAL_DAMAGE 20
#define PLAYER_SPECIAL_DELAY 50
#define PLAYER_AUDIO_DELAY 5
#define PLAYER_SHIP_HEIGHT 16
#define PLAYER_SHIP_WIDTH 16
#define PLAYER_SHIP_CENTER_FRAME 0
#define PLAYER_SHIP_LEFT_FRAME 160
#define PLAYER_SHIP_RIGHT_FRAME 320
#define PLAYER_MOVE_SPEED 2
#define PLAYER_CENTER_OFFSET_X 8
#define PLAYER_CENTER_OFFSET_Y 8
#define PLAYER_HITBOX_OFFSET_X 5
#define PLAYER_HITBOX_OFFSET_Y 6
#define PLAYER_HITBOX_WIDTH 8
#define PLAYER_HITBOX_HEIGHT 8
#define PLAYER_INVINCIBLE_TIME 128

#define ENGINE_HEIGHT 5
#define ENGINE_WIDTH 16
#define ENGINE_ANIM_FRAMES 8